package uz.pdp.englishlanguages_2.utils;

public interface MessageConstants {

    String LOGIN_OR_PASSWORD_ERROR = "LOGIN OR PASSWORD ERROR";
    String USER_NOT_FOUND = "USER NOT FOUND";
    String PASSWORD_CAN_NOT_BE_EMPTY = "PASSWORD CAN NOT BE EMPTY";
    String PASSWORD_SHOULD_MATCH_REGEX = "PASSWORD SHOULD MATCH REGEX";
    String USER_PERMISSION_RESTRICTION = "USER PERMISSION RESTRICTION";
    String TOKEN_NOT_VALID = "TOKEN NOT VALID";
    String REFRESH_TOKEN_EXPIRED = "REFRESH TOKEN EXPIRED";
    String WRONG_ACCESS_TOKEN = "WRONG ACCESS TOKEN";
    String ACCESS_TOKEN_NOT_EXPIRED = "ACCESS TOKEN NOT EXPIRED";
    String DO_NOT_HAVE_PERMISSION_TO_USE_THIS_WAY = "DO NOT HAVE PERMISSION TO USE THIS_WAY";
    String PAGE_NOT_FOUND = "PAGE NOT FOUND";
    String METHOD_ERROR = "METHOD ERROR";
    String UNACCEPTABLE = "UNACCEPTABLE";

    String EMAIL_CAN_NOT_BE_EMPTY = "EMAIL_CAN_NOT_BE_EMPTY";
    String FIRST_NAME_CAN_NOT_BE_EMPTY = "FIRST NAME CAN NOT BE EMPTY";
    String LAST_NAME_CAN_NOT_BE_EMPTY = "LAST NAME CAN NOT BE EMPTY";
    String EMAIL_SHOULD_MATCH_REGEX = "EMAIL SHOULD MATCH REGEX";
    String PRE_PASSWORD_CAN_NOT_BE_EMPTY = "PRE PASSWORD CAN NOT BE EMPTY";
    String PRE_PASSWORD_SHOULD_MATCH_REGEX = "PRE PASSWORD SHOULD MATCH REGEX";

    String FULLNAME_CANNOT_BE_EMPTY = "FULLNAME CANNOT BE EMPTY";
    String BIRTHDATE_CANNOT_BE_EMPTY = "BIRTHDATE CANNOT BE EMPTY";

    String UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS";

    String REFRESH_TOKEN_CAN_NOT_BE_EMPTY = "REFRESH TOKEN CAN NOT BE EMPTY";
    String ACCESS_TOKEN_CAN_NOT_BE_EMPTY = "ACCESS TOKEN CAN NOT BE EMPTY";
    String ADDRESS_CANNOT_BE_EMPTY = "ADDRESS CANNOT BE EMPTY";
    String DISTRICT_NOT_FOUND = "DISTRICT NOT FOUND";
    String PASSWORDS_DO_NOT_MATCH = "PASSWORDS DO NOT MATCH";

    String ROLE_NAME_CAN_NOT_BE_EMPTY = "ROLE NAME CAN NOT BE EMPTY";
    String USER_NOT_VERIFIED = "USER NOT VERIFIED";
    String THE_USER_WITH_THIS_PHONE_NUMBER_DOES_NOT_EXIST = "THE USER WITH THIS PHONE NUMBER DOES NOT EXIST";

    String SOMETHING_WENT_WRONG = "SOMETHING WENT WRONG";
    String PHONE_NUMBER_CAN_NOT_BE_EMPTY = "PHONE NUMBER CAN NOT BE EMPTY";

    String SUCCESSFUL_VERIFICATION = "SUCCESSFUL VERIFICATION";
    String TIME_OUT = "TIME OUT";
    String NOT_MATCH = "VERIFICATION PASSWORD NOT MATCH";
    String SUCCESSFUL_UPDATED = "SUCCESSFUL UPDATED";
    String DATA_NOT_FOUND =  "DATA NOT FOUND WIH THIS ID : %s";
    String DATA_ALREADY_EXISTS =  "DATA ALREADY EXISTS WITH %s";
    String UNIVERSAL_NOT_FOUND = "%s NOT FOUND WITH %s : %s";
    String INVALID_UZBEK_PHONE_NUMBER = "INVALID UZBEK PHONE NUMBER";
    String REQUIRED_VERIFICATION_CODE = "VERIFICATION CODE IS REQUIRED";


    String USER_ALREADY_EXISTS = "USER ALREADY EXISTS";
}
